name: CI PIPELINE

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout_code
      uses: actions/checkout@v3

    - name: Set_up_Node_js
      uses: actions/setup-node@v3
      with:
          node-version: 16
      
    - name: Install dependencies
      run:  npm install

    - name: run_test
      run: npm test